version: "3.5"

x-anton-rewrites: &anton-rewrites
  build: .
  image: "${IMAGE_NAME:-anton}:${IMAGE_TAG:-latest}"

services:
  indexer:
    <<: *anton-rewrites
  rescan:
    <<: *anton-rewrites
  web:
    <<: *anton-rewrites
  migrations:
    <<: *anton-rewrites
  clickhouse:
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8123:8123"